### ISSUE TITLE
Could not find gem 'scss_lint'

### ISSUE THREAD

**Issue by msharp1** [crispgm/resume#11]
- [ ] I believe this to be a bug, not a question about using Crisp Minimal Résumé.
- [ ] This is a feature request.

---

## My OS

- [ ] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Ubuntu*** GNU/Linux (20.04)
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

## My Ruby/Jekyll Version

ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
jekyll --version
jekyll 4.2.0

---

## My Issue

- [ ] I cannot install Gem.
- [ ] I cannot run/debug the theme locally.
- [ ] My résumé does not render correctly.
- [ ] My résumé has problem with Github Pages.
- [X] Other. (Replace with your description here.)

`scss_lint` gem cannot be found

## My Reproduction Steps

- Follow https://jekyllrb.com/docs/installation/ubuntu/
- git clone https://github.com/crispgm/resume.git
- cd resume
- jekyll serve

I get:
```
Traceback (most recent call last):
	15: from /home/martin/gems/bin/jekyll:23:in `<main>'
	14: from /home/martin/gems/bin/jekyll:23:in `load'
	13: from /home/martin/gems/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
	12: from /home/martin/gems/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	11: from /usr/lib/ruby/2.7.0/bundler.rb:149:in `setup'
	10: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
	 9: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
	 8: from /usr/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
	 7: from /usr/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
	 6: from /usr/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
	 5: from /usr/lib/ruby/2.7.0/bundler/definition.rb:258:in `resolve'
	 4: from /usr/lib/ruby/2.7.0/bundler/resolver.rb:22:in `resolve'
	 3: from /usr/lib/ruby/2.7.0/bundler/resolver.rb:49:in `start'
	 2: from /usr/lib/ruby/2.7.0/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!'
	 1: from /usr/lib/ruby/2.7.0/bundler/resolver.rb:258:in `each'
/usr/lib/ruby/2.7.0/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'scss_lint' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)

```

**Comment by crispgm** [comment]
please use `bundle exec jekyll serve`, because `scss_lint` is declared to be required by Gemfile.
