### ISSUE TITLE
how to change color scheme?

### ISSUE THREAD

**Issue by HarrisonFarah** [crispgm/resume#12]
- [X] I believe this to be a bug, not a question about using Crisp Minimal Résumé.

---

## My OS

- [X] I am on (or have tested on) ***Windows*** 10+

## My Ruby/Jekyll Version

Ruby: 2.7.4
Jekyll: 3.9.1

## My Issue

- [X ] My résumé wont process "color: red" in _config.yml

## My Reproduction Steps

1. Step 1
2. Step 2
3. Step 3

**Comment by crispgm** [comment]
@HarrisonFarah `color` may be specified in `_config.yml`, e.g.:
```yaml
color: nord
```

Refers here: https://github.com/crispgm/resume#colors

**Comment by HarrisonFarah** [comment]
there is no line or code with color: nord on your repo. I did it to my repo
and i could not change the color scheme when i put in red or pink

**Comment by crispgm** [comment]
> there is no line or code with color: nord on your repo. I did it to my repo and i could not change the color scheme when i put in red or pink
> […](#)

There is a default color, so you may by yourself. And then follow the color name in this file: https://github.com/HarrisonFarah/resume/blob/master/assets/css/resume.scss

**Comment by HarrisonFarah** [comment]
so if I put color: red in my config.yml it won’t work

**Comment by crispgm** [comment]
Based on your forked repo https://github.com/HarrisonFarah/resume, I think you accidentally break the CSS path. You should set base URL to `baseurl: "/resume/"` to fix that.
