### ISSUE TITLE
can't buy you a coffee, 404

### ISSUE THREAD

**Issue by huahuayu** [crispgm/resume#5]
https://www.buymeacoffee.com/crispgm 404 error
**
![image](https://user-images.githubusercontent.com/1725060/60226796-5a241380-98bf-11e9-98f6-23055e5ee20e.png)
**

**Comment by crispgm** [comment]
Thanks for reaching this page. There is a problem with my payment method and I contact BuyMeACoffee but it unluckily hasn't respond to me. If you want to do this, please consider use the PayPal link instead on the bottom of the README <https://github.com/crispgm/resume#donation>.
