### ISSUE TITLE
Chinese resume 

### ISSUE THREAD

**Issue by huahuayu** [crispgm/resume#6]
hi, the resume is beautiful and clean, I really love it, I suggest you add Chinese resume demo, or, Chinese and English resume can switch by hyperlink.  More robust.

**Comment by Duosl** [comment]
I think you can look the Chinese README,  or to edit the file of '_data/resume.yml' with Chinese. I think this can meet your requirements.

**Comment by crispgm** [comment]
@huahuayu https://crispgm.github.io/resume/resume_zh-CN.html
here is the demo, and I just notice that it is broken maybe from last month. And it fixed. Thank you all!

**Comment by crispgm** [comment]
@Duosl that's true. and actually I provide a Chinese version, with its own `_data/resume_zhcn.yml`, `_layout/resume_zh_cn.yml`, `resume_zh-CN.html`.
